import { addDoc, collection, doc, getDocs, updateDoc } from 'firebase/firestore';
import { db } from './firebaseConfig';
import type { Connection, ConnectionStatus } from '../src/constants/types';

const COLLECTION = 'contacts';

/**
 * Add a new contact/connection. The id is generated by Firestore and returned.
 * New contacts start life as `pending` until the invite is accepted.
 */
export async function addContact(
  contact: Omit<Connection, 'id' | 'status'> & { status?: ConnectionStatus },
): Promise<string> {
  const ref = await addDoc(collection(db, COLLECTION), {
    ...contact,
    status: contact.status ?? 'pending',
  });
  return ref.id;
}

/**
 * Get every saved contact, sorted alphabetically by name.
 */
export async function getContacts(): Promise<Connection[]> {
  const snap = await getDocs(collection(db, COLLECTION));
  return snap.docs
    .map((d) => ({ ...(d.data() as Omit<Connection, 'id'>), id: d.id }))
    .sort((a, b) => a.name.localeCompare(b.name));
}

/**
 * Move a contact between invite states (e.g. `pending` -> `active` once the
 * invite is accepted, or `pending` -> `declined`).
 */
export async function updateContactStatus(
  id: string,
  status: ConnectionStatus,
): Promise<void> {
  await updateDoc(doc(db, COLLECTION, id), { status });
}
