import { addDoc, collection, doc, getDocs, query, updateDoc, where } from 'firebase/firestore';
import { db } from './firebaseConfig';
import type {
  Connection,
  ConnectionGroup,
  ConnectionRelationship,
  ConnectionStatus,
} from '../src/constants/types';

const COLLECTION = 'contacts';

/**
 * Add a new contact/connection. The id is generated by Firestore and returned.
 * New contacts start life as `pending` until the invite is accepted.
 */
export async function addContact(
  contact: Omit<Connection, 'id' | 'status'> & { status?: ConnectionStatus },
): Promise<string> {
  const ref = await addDoc(collection(db, COLLECTION), {
    ...contact,
    status: contact.status ?? 'pending',
    // Written explicitly rather than left undefined: a Firestore where('group')
    // query skips documents that lack the field entirely.
    group: contact.group ?? 'other',
  });
  return ref.id;
}

/**
 * Get the contacts belonging to one profile, sorted alphabetically by name.
 *
 * Scoped by ownerId: without it every device saw every contact in the database.
 * Contacts written before ownerId existed have no owner and are excluded.
 */
export async function getContacts(ownerId: string): Promise<Connection[]> {
  const snap = await getDocs(
    query(collection(db, COLLECTION), where('ownerId', '==', ownerId)),
  );
  return snap.docs
    .map((d) => ({ ...(d.data() as Omit<Connection, 'id'>), id: d.id }))
    .sort((a, b) => a.name.localeCompare(b.name));
}

/**
 * Invite an existing Konekt profile. Unlike a typed-in contact this carries the
 * invitee's profileId, which is what lets recaps be addressed to them.
 */
export async function inviteProfile(params: {
  ownerId: string;
  ownerName: string;
  profileId: string;
  name: string;
  relationship?: ConnectionRelationship;
}): Promise<string> {
  const ref = await addDoc(collection(db, COLLECTION), {
    ownerId: params.ownerId,
    ownerName: params.ownerName,
    profileId: params.profileId,
    name: params.name,
    relationship: params.relationship ?? 'other',
    group: 'other' as ConnectionGroup,
    status: 'pending' as ConnectionStatus,
  });
  return ref.id;
}

/**
 * Invites addressed TO this profile — the receiving end of the relationship.
 *
 * getContacts() reads by ownerId and so only ever returns invites you sent;
 * without this query the invited person could never see, let alone accept, an
 * invite. Accepting is what authorises the sender to deliver recaps, so it has
 * to happen on the invitee's own account.
 */
export async function getIncomingInvites(profileId: string): Promise<Connection[]> {
  const snap = await getDocs(
    query(collection(db, COLLECTION), where('profileId', '==', profileId)),
  );
  return snap.docs
    .map((d) => ({ ...(d.data() as Omit<Connection, 'id'>), id: d.id }))
    .sort((a, b) => (a.ownerName ?? '').localeCompare(b.ownerName ?? ''));
}

/**
 * Move a contact between invite states (e.g. `pending` -> `active` once the
 * invite is accepted, or `pending` -> `declined`).
 */
export async function updateContactStatus(
  id: string,
  status: ConnectionStatus,
): Promise<void> {
  await updateDoc(doc(db, COLLECTION, id), { status });
}

/**
 * File a connection under Family, Friends or Other. Only the owner of a
 * connection can group it — it's their own filing, not a label on the person.
 */
export async function updateContactGroup(id: string, group: ConnectionGroup): Promise<void> {
  await updateDoc(doc(db, COLLECTION, id), { group });
}
