import { addDoc, collection, getDocs } from 'firebase/firestore';
import { db } from './firebaseConfig';
import type { Connection } from '../src/constants/types';

const COLLECTION = 'contacts';

/**
 * Add a new contact/connection. The id is generated by Firestore and returned.
 */
export async function addContact(contact: Omit<Connection, 'id'>): Promise<string> {
  const ref = await addDoc(collection(db, COLLECTION), contact);
  return ref.id;
}

/**
 * Get every saved contact, sorted alphabetically by name.
 */
export async function getContacts(): Promise<Connection[]> {
  const snap = await getDocs(collection(db, COLLECTION));
  return snap.docs
    .map((d) => ({ ...(d.data() as Omit<Connection, 'id'>), id: d.id }))
    .sort((a, b) => a.name.localeCompare(b.name));
}
