import { addDoc, collection, getDocs } from 'firebase/firestore';

import { db } from './firebaseConfig';
import type { Profile } from '../src/constants/types';

const COLLECTION = 'profiles';

/**
 * Create a profile (the app user's own identity). The id is generated by
 * Firestore and returned.
 */
export async function createProfile(name: string): Promise<string> {
  const ref = await addDoc(collection(db, COLLECTION), {
    name,
    createdAt: Date.now(),
  });
  return ref.id;
}

/**
 * Get every created profile. Not used yet — for when People can look up a
 * real profile instead of a manually-entered contact.
 */
export async function getProfiles(): Promise<Profile[]> {
  const snap = await getDocs(collection(db, COLLECTION));
  return snap.docs.map((d) => ({ ...(d.data() as Omit<Profile, 'id'>), id: d.id }));
}
